### ISSUE TITLE
update README and rename project

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/automated-walk-bike-counter#15]
this README and the project name a little still in the tooth. Let's go ahead and update to reflect scope of the project

**Comment by ian-r-rose** [comment]
What about either "walk-bike-counter" or "walk-bike-ticker", to reflect LADOT's [new nomenclature](https://ladot.lacity.org/walk-bike-count)?

**Comment by hunterowens** [comment]
maybe something like "automated-walk-bike-counter"?

**Comment by ian-r-rose** [comment]
I think that's fine, though maybe feels a bit long to type "`import automated_walk_bike_counter as awbc`".

Any thoughts @vahedi25411 @mpourhoma? Also, are you getting these notifications? You may want to watch the repo if not.

**Comment by vahedi25411** [comment]
I get notification just when you mention me on a post otherwise I am not notified that there is a new thread to participate. 

Personally speaking, I like "automated-walk-bike-counter".

**Comment by ian-r-rose** [comment]
If you want to be notified for all posts, you can click the "Watching" button in the upper right corner of the GitHub UI

**Comment by vahedi25411** [comment]
I did.
Thanks
