### ISSUE TITLE
Consider using black for code formatting

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#22]
[black](https://github.com/psf/black) is a python code formatter that has recently gotten a lot of buy-in from the python community. Any interest in applying it to this codebase?

**Comment by ian-r-rose** [comment]
Any thoughts on this @vahedi25411?

**Comment by vahedi25411** [comment]
I haven't seen it before. Let me take a look and I will let you know my ideas about it.

**Comment by ian-r-rose** [comment]
Fixed by #30
