### ISSUE TITLE
setup CI / CD? 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/automated-walk-bike-counter#24]

**Comment by ian-r-rose** [comment]
Would like to move on this, but I think the ability to run headless (#31) would make it easier to do.

**Comment by vahedi25411** [comment]
I think if we want to have it, we should have for both cases.

**Comment by vahedi25411** [comment]
Or you want just make sure that the code is ready for deployment on the servers automatically?

**Comment by ian-r-rose** [comment]
I'd certainly be in favor of testing both cases, I'm just less sure of how to test a tkinter app. A CLI-driven one should be fairly straightforward, however.

**Comment by vahedi25411** [comment]
In the GUI version, we have some actions in which the user can interact with the application. Can we test the result of these actions?

**Comment by ian-r-rose** [comment]
Possibly, but I'm unsure how. I have more experience with testing non-GUI python apps.

**Comment by vahedi25411** [comment]
If you tell me what you need to make it ready, I may be able to help in some way.

**Comment by ian-r-rose** [comment]
In the short-term, I'd like to try getting the headless portion of this tested.

**Comment by hunterowens** [comment]
I think this is done?

**Comment by ian-r-rose** [comment]
Yes, this is done.
