### ISSUE TITLE
Remove darknet

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#25]
The codebase has a number of references to darknet, which, as far as I know, is no longer used. We should remove those.

**Comment by ian-r-rose** [comment]
Or am I incorrect that darknet is no longer used?

**Comment by vahedi25411** [comment]
Yes you are right. It should have left from the days that we were using darknet. Now we don't use it anymore. But please let me know where are they to make sure that we don't need them.

**Comment by ian-r-rose** [comment]
I see [this](https://github.com/CityOfLosAngeles/automated-walk-bike-counter/blob/55cdabecbbe09a316aad05a4c98d6e5a062fde89/automated_walk_bike_counter/utils/layer_utils.py#L33-L77) utility function, though it appears to be used right now in `model.py`. Maybe I just don't understand the naming convention, or it has an old name?

**Comment by vahedi25411** [comment]
I will check this out and let you know the result.

**Comment by hunterowens** [comment]
@vahedi25411 checking back in on this

**Comment by vahedi25411** [comment]
I have already checked the code and I am 100 percent sure that our code does not have any dependency on Darknet.

**Comment by hunterowens** [comment]
closing! Thanks @vahedi25411
