### ISSUE TITLE
Ability to run headless

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#31]
The GUI is currently a very nice way to kick off a count, allowing you to select a video, AOI, and parameters. However, once we are running with something more like real-time data, we would like to be able to take the same choices that we made in the gui, and run them headlessly. At a minimum we need to make sure of the following:

1. We can specify the video or video stream via a CLI argument or config file.
1. We can specify an AOI geometry
1. We can specify an output stream for counts.
1. All of the above can run without tkinter or x11.

**Comment by vahedi25411** [comment]
Yes, I agree. We can have both versions at the same time and I think it is not a big deal to add the CLI version to this code.

**Comment by ian-r-rose** [comment]
@vahedi25411 Is there any ongoing work on this? I can also put some cycles into it with some guidance.

**Comment by ian-r-rose** [comment]
Any updates here?

**Comment by vahedi25411** [comment]
Not yet actually, I am going to work on it and let you know the result in the next couple of days.

**Comment by ian-r-rose** [comment]
Hi @vahedi25411, any updates, or things I can do to help move this along? It would be great to see a branch for this, even if incomplete.

**Comment by vahedi25411** [comment]
[Here ](https://github.com/CityOfLosAngeles/automated-walk-bike-counter/tree/command-line)is the new branch that has the changes for the command-line.

**Comment by vahedi25411** [comment]
@ian-r-rose It can be run like this:

automated-walk-bike-counter --file_name="..\data\sample7.mp4" --aoi=10,10;1000,10;1000,700;10,700

**Comment by ian-r-rose** [comment]
Great, thanks @vahedi25411! Is it ready for a PR, or are you still working on it?

**Comment by ian-r-rose** [comment]
Looks like there are merge conflicts with #42, can you do a merge or rebase?

**Comment by vahedi25411** [comment]
Actually, there is a special case in one video that I was still working on it but couldn't find the problem. Apart from that, it is working fine.

**Comment by hunterowens** [comment]
@ian-r-rose @vahedi25411 ready to close this one?

**Comment by ian-r-rose** [comment]
Yep!
