### ISSUE TITLE
Code entry point

### ISSUE THREAD

**Issue by vahedi25411** [CityOfLosAngeles/automated-walk-bike-counter#33]
In your revised version of the code, I could not find the file that I used to run the application. I would like to know is it created when the application is installed?

Apart from that, I would like to know how should I install the code for the first time on a computer. Should I install the environment by myself and then install the app?

**Comment by ian-r-rose** [comment]
Sorry to not be clear about this @vahedi25411, I'm still working on updating the `README.md`.

The entrypoint is now an executable that can be invoked from the command line. This is installed when you [install the application](https://github.com/CityOfLosAngeles/automated-walk-bike-counter/blob/22827713740b1932c02c8a9195b139c4b050973f/setup.py#L59). I'll write this up in a more detailed way, but briefly:

1. Create a new environment with the dependencies. You can do this in whatever way you like, and I presume you already have one, but one option is to do
```
conda create -f environment.yml
```
2. Install the app with `pip install -e .[develop]`.
3. Run `automated-walk-bike-counter` on the command line.

**Comment by vahedi25411** [comment]
I have already done it and this is the result:

Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining pip:  18%|███████████▉                                                      | 28/155 [00:30<07:05,  3.35s/i\ | omparing specs that have this dependency:  36%|██████████████▌                         | 4/11 [00:36<01:04,  9.18s/i/
Examining python:  27%|█████████████████                                              | 42/155 [01:28<04:45,  2.53s/it]-\ mparing specs that have this dependency:   0%|                                                | 0/11 [00:00<?, ?it/| -failed                                                                                                                 /                                                                                                                       |UnsatisfiableError: The following specifications were found to be incompatible with each other:                        /


Package wincertstore conflicts for:
munkres=1.0.12 -> python -> pip -> setuptools -> wincertstore[version='>=0.2']
tqdm=4.36.1 -> python -> pip -> setuptools -> wincertstore[version='>=0.2']
pip=19.3.1 -> setuptools -> wincertstore[version='>=0.2']
pykalman=0.9.5 -> python -> pip -> setuptools -> wincertstore[version='>=0.2']
requests=2.22 -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
python=3.6.7 -> pip -> setuptools -> wincertstore[version='>=0.2']
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools -> wincertstore[version='>=0.2']
fsspec=0.5.2 -> python[version='>=3.5'] -> pip -> setuptools -> wincertstore[version='>=0.2']
tensorflow=1.13.1 -> grpcio[version='>=1.8.6'] -> setuptools -> wincertstore[version='>=0.2']
Package pip conflicts for:
requests=2.22 -> python[version='>=2.7,<2.8.0a0'] -> pip
python=3.6.7 -> pip
tensorflow=1.13.1 -> python=3.7 -> pip
pykalman=0.9.5 -> python -> pip
tqdm=4.36.1 -> python -> pip
fsspec=0.5.2 -> python[version='>=3.5'] -> pip
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> pip
munkres=1.0.12 -> python -> pip
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> python[version='>=3.7,<3.8.0a0'] -> pip
pip=19.3.1
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> pip
Package ca-certificates conflicts for:
tqdm=4.36.1 -> python -> ca-certificates
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> ca-certificates
pykalman=0.9.5 -> python -> ca-certificates
munkres=1.0.12 -> python -> ca-certificates
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> ca-certificates
opencv=4.1.2 -> libopencv==4.1.2=h7e61296_0 -> qt=5.12 -> openssl[version='>=1.1.1c,<1.1.2a'] -> ca-certificates
fsspec=0.5.2 -> python[version='>=3.5'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
python=3.6.7 -> pip -> requests -> urllib3[version='>=1.21.1,<1.24'] -> cryptography[version='>=1.3.4'] -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
tensorflow=1.13.1 -> python=3.7 -> ca-certificates
pip=19.3.1 -> python[version='>=3.8,<3.9.0a0'] -> ca-certificates
requests=2.22 -> urllib3[version='>=1.21.1,<1.25'] -> ca-certificates
Package python conflicts for:
pykalman=0.9.5 -> python[version='2.7.*|3.5.*']
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> python[version='3.6.*|>=3.6,<3.7.0a0']
tensorflow=1.13.1 -> python[version='3.6.*|3.7.*|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
tqdm=4.36.1 -> python
munkres=1.0.12 -> python
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> python[version='>=3.7,<3.8.0a0']
requests=2.22 -> urllib3[version='>=1.21.1,<1.25'] -> ipaddress -> python[version='<=3.3']
fsspec=0.5.2 -> python[version='>=3.5']
tensorflow=1.13.1 -> tensorflow-estimator[version='>=1.13.0,<1.14.0a0'] -> mock[version='>=2.0.0'] -> pbr[version='>=1.3'] -> pip -> requests -> urllib3[version='>=1.21.1,<1.24'] -> ipaddress -> python[version='<=3.3']
pillow=6.2.1 -> olefile -> python[version='2.7.*|3.6.*']
configargparse=0.14 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
tensorflow=1.13.1 -> grpcio[version='>=1.8.6'] -> setuptools -> python[version='2.7.*|3.5.*']
pip=19.3.1 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
requests=2.22 -> certifi[version='>=2017.4.17'] -> python[version='2.7.*|3.6.*']
pillow=6.2.1 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
tensorflow=1.13.1 -> numpy[version='>=1.13.3'] -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0']
requests=2.22 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
python=3.6.7
pykalman=0.9.5 -> numpy -> python[version='3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
pip=19.3.1 -> setuptools -> python[version='2.7.*|3.6.*']
Package msgpack-python conflicts for:
python=3.6.7 -> pip -> cachecontrol -> msgpack-python
pykalman=0.9.5 -> python -> pip -> cachecontrol -> msgpack-python
fsspec=0.5.2 -> python[version='>=3.5'] -> pip -> cachecontrol -> msgpack-python
requests=2.22 -> python[version='>=2.7,<2.8.0a0'] -> pip -> cachecontrol -> msgpack-python
tqdm=4.36.1 -> python -> pip -> cachecontrol -> msgpack-python
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> pip -> cachecontrol -> msgpack-python
munkres=1.0.12 -> python -> pip -> cachecontrol -> msgpack-python
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> pip -> cachecontrol -> msgpack-python
Package setuptools conflicts for:
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools
fsspec=0.5.2 -> python[version='>=3.5'] -> pip -> setuptools
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools
tensorflow=1.13.1 -> tensorboard[version='>=1.13.0,<1.14.0'] -> markdown[version='>=2.6.8'] -> setuptools[version='>=36']
python=3.6.7 -> pip -> setuptools
tqdm=4.36.1 -> python -> pip -> setuptools
munkres=1.0.12 -> python -> pip -> setuptools
pip=19.3.1 -> setuptools
requests=2.22 -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools
pykalman=0.9.5 -> python -> pip -> setuptools
tensorflow=1.13.1 -> grpcio[version='>=1.8.6'] -> setuptools
Package certifi conflicts for:
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
munkres=1.0.12 -> python -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
python=3.6.7 -> pip -> requests -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
tensorflow=1.13.1 -> python=3.7 -> pip -> requests -> certifi[version='>=2017.4.17']
tensorflow=1.13.1 -> grpcio[version='>=1.8.6'] -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
fsspec=0.5.2 -> python[version='>=3.5'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
tqdm=4.36.1 -> python -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
requests=2.22 -> python[version='>=2.7,<2.8.0a0'] -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
requests=2.22 -> certifi[version='>=2017.4.17']
pykalman=0.9.5 -> python -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26|>=2017.4.17']
Package wheel conflicts for:
pillow=6.2.1 -> python[version='>=3.7,<3.8.0a0'] -> pip -> wheel
configargparse=0.14 -> python[version='>=3.6,<3.7.0a0'] -> pip -> wheel
pip=19.3.1 -> wheel
fsspec=0.5.2 -> python[version='>=3.5'] -> pip -> wheel
pykalman=0.9.5 -> python -> pip -> wheel
tensorflow=1.13.1 -> python=3.7 -> pip -> wheel
munkres=1.0.12 -> python -> pip -> wheel
opencv=4.1.2 -> py-opencv==4.1.2=py37h5ca1d4c_0 -> python[version='>=3.7,<3.8.0a0'] -> pip -> wheel
python=3.6.7 -> pip -> wheel
requests=2.22 -> python[version='>=2.7,<2.8.0a0'] -> pip -> wheel
tqdm=4.36.1 -> python -> pip -> wheel
Package libpython conflicts for:
tensorflow=1.13.1 -> keras-applications[version='>=1.0.6'] -> keras[version='>=2.1.6'] -> theano -> libpython[version='>=2.0']

What should I do next?

**Comment by ian-r-rose** [comment]
On the command line, run `automated-walk-bike-counter`. Does this produce any errors?

**Comment by vahedi25411** [comment]
'automated-walk-bike-counter' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ian-r-rose** [comment]
Hmm, there may be some cross-platform compatibility issues with the console script that we need to nail down.

Does it work if you change `gui_scripts` in the setup.py to `console_scripts`, then reinstall?

**Comment by ian-r-rose** [comment]
(the entrypoint is `automated_walk_bike_counter.gui.app:main`)

**Comment by ian-r-rose** [comment]
Oh, I missed it above. It looks like the install failed. What kind of machine are you running on?

**Comment by vahedi25411** [comment]
I am running on Windows.
I am running these commands in anaconda prompts. Is doing this correct?

**Comment by ian-r-rose** [comment]
I usually use bash on Windows (either git-bash or WSL), but I'd imagine it could be done with anaconda prompts as well.

If you already have a working environment, you can try skipping the first step and run `pip install -e .[develop]`.

**Comment by vahedi25411** [comment]
My next question was that, if we have a setup process to install the application, how we can decide to install using GPU or CPU?

**Comment by ian-r-rose** [comment]
I think, as long as the imports are the same, we should be able to customize the environments on a per-deployment basis. With the `environment.yml` I just wanted to document a working CPU-based environment, rather than absolute requirements.

**Comment by vahedi25411** [comment]
The imports are the same but the requirements are different. For example, for running `Tensorflow` on `GPU` I have to install `Cuda` and `TensorFlow` for `GPU`.

**Comment by ian-r-rose** [comment]
Right, so I would want to have a very specific `environment.yml` for a specific deployment, but I think we can probably relax the one in this repo a bit.

**Comment by vahedi25411** [comment]
Sure.

Right now I have an environment that has already configured to be used on GPU. So, can I run your setup on my environment or it may cause conflicts?

**Comment by ian-r-rose** [comment]
I *think* it would be okay, it would just install a few extra python-only dependencies.

**Comment by ian-r-rose** [comment]
Such as `configargparse`, `fsspec`, etc.

**Comment by vahedi25411** [comment]
Thanks for your time and support.

**Comment by ian-r-rose** [comment]
No problem! Thanks for debugging with me! I would like to get this to a place where we can relatively easily install it in a range of environments.

**Comment by vahedi25411** [comment]
Considering your changes in the code I can say that this place is close.

**Comment by ian-r-rose** [comment]
I'm going to see if I can figure out an environment that works for both Windows and Linux.

**Comment by ian-r-rose** [comment]
@vahedi25411 Did you get the entry point working? Do you think a working windows `environment.yml` would solve the problem?

**Comment by vahedi25411** [comment]
Not really, I am preparing the application for CoMotion. So I don't want to check it on my environment right now to prevent any possible issues. I will do it later.

**Comment by ian-r-rose** [comment]
@vahedi25411 can this be closed?

**Comment by vahedi25411** [comment]
Yes, it can be closed.
