### ISSUE TITLE
Include webcam work

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#35]
Last week @vahedi25411 demo'd some nice work which allowed the user to hook up a webcam to the application. Can we make a PR of that here?

**Comment by vahedi25411** [comment]
Sure. I did it in rush and I need to make the code clean and after that, I will push my changes.

**Comment by ian-r-rose** [comment]
Also a good time to try the new pre-commit hooks!

**Comment by vahedi25411** [comment]
That's right. But the problem is that I have to finish my thesis in two weeks and be prepared to defend. So, I am pretty busy these days and I am going to make these changes after it.

**Comment by ian-r-rose** [comment]
Is there anything in particular that you think would be useful to push on while you are in thesis mode?

**Comment by vahedi25411** [comment]
I don't have anything in my mind now. if I found anything particular I would let you know.

**Comment by vahedi25411** [comment]
@ian-r-rose I downloaded the latest version of the code and followed the steps you mentioned in the readme file in order to create a new environment, install the packages and run the project.
After adding my changes to the code, I run the project again but I can't see the changes that I have made. Is there anything else I should do to see the changes in the executable version?

**Comment by ian-r-rose** [comment]
You may need to do an editable install: `pip install -e .`

**Comment by vahedi25411** [comment]
I did this `pip install -e .[develop]`.
But after changing the code.

**Comment by vahedi25411** [comment]
And now the application does not run at all.

**Comment by ian-r-rose** [comment]
Does it run without your changes?

**Comment by vahedi25411** [comment]
I could run it after making changes. But after `pip install -e .[develop].` it does not run.

**Comment by ian-r-rose** [comment]
Does the current `master` branch run?

**Comment by vahedi25411** [comment]
No, it does not.

**Comment by ian-r-rose** [comment]
What happens? Saying it does not run does not give me much to go on. I can make sure the dependencies are installed via `conda` with
```
conda env update -f environment.yml
```
Once that is set up, I install with
```
pip install -e .
```
Launching with
```
automated-walk-bike-counter
```
brings up the user interface. I'm still confused what exactly the problem is. Is it that the current master doesn't run, or that you need changes to make it run, or that it doesn't run after you make changes, or something else?

**Comment by vahedi25411** [comment]
I created the environment using: `conda env update -f environment.yml`

Then I executed: `pip install .`

Then I could launch the GUI by running `automated-walk-bike-counter'

I made some changes in code and launched the app again to see the changes using `automated-walk-bike-counter` but I didn't see the changes in GUI.

I thought that it may be because of the steps I missed, so I executed `pip install -e .[develop]` and `pre-commit install`.

At this point, I couldn't launch the app using `automated-walk-bike-counter` anymore.

**Comment by ian-r-rose** [comment]
The first time you installed it you did a non-editable install, so it makes sense that you wouldn't see changes, since it is not running off of the local copy.

Then you made some changes, which I haven't seen, so I don't know if the problem is there. Can you confirm that you can make an editable install (`pip install -e .`) *without* any changes to master?

**Comment by vahedi25411** [comment]
Yes, I can make an editable install (`pip install -e .`) without any changes to the master.

**Comment by ian-r-rose** [comment]
And it works?

**Comment by vahedi25411** [comment]
Yes, but after that `automated-walk-bike-counter` doesn't do anything.

**Comment by ian-r-rose** [comment]
No output to the console? What if you go back to a non-editable install? I don't have much to go on here.

**Comment by ian-r-rose** [comment]
You can also try starting fresh by uninstalling first (`pip uninstall automated-walk-bike-counter`)

**Comment by vahedi25411** [comment]
Ok, let's do this.

**Comment by vahedi25411** [comment]
I uninstalled the app and also removed the environment and installed everything from scratch.

`conda env update -f environment.yml`

`pip install .` or `pip install -e .`

`automated-walk-bike-counter`

Still, the GUI does not show up.

**Comment by ian-r-rose** [comment]
But with which branch? `master`, or `master` with your modifications?

**Comment by ian-r-rose** [comment]
I'm trying to isolate where the problem is. I can't reproduce your issue because it works fine on my machine (both on windows and WSL).

**Comment by vahedi25411** [comment]
It was master with my modification, but before this I created a new branch and moved my changes to a new branch.
So in this case, it was master without my modification.

**Comment by ian-r-rose** [comment]
And there are no errors on the console?

**Comment by ian-r-rose** [comment]
Can you push your changes here so I can try them?

**Comment by ian-r-rose** [comment]
(to a branch, I mean)

**Comment by vahedi25411** [comment]
Let me clone one more time first and then I will push my code.

**Comment by ian-r-rose** [comment]
Pushing work-in-progress code is no problem!

**Comment by vahedi25411** [comment]
My changes are in real-time branch.

**Comment by ian-r-rose** [comment]
I see the following error when I run that branch:

```python
Traceback (most recent call last):
  File "/home/ian/anaconda3/envs/automated-walk-bike-counter/bin/automated-walk-bike-counter", line 11, in <module>
    load_entry_point('automated-walk-bike-counter', 'gui_scripts', 'automated-walk-bike-counter')()
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/gui/app.py", line 34, in main
    app = Application()
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/gui/app.py", line 25, in __init__
    self.controller = MainController()
  File "/mnt/c/Users/itacid457/repos/automated-walk-bike-counter/automated_walk_bike_counter/gui/controller/main_controller.py", line 37, in __init__
    self.internal_webcam = IntVar()
NameError: name 'IntVar' is not defined
```

Does this not output for you?

**Comment by vahedi25411** [comment]
No, I can not see this error.

**Comment by vahedi25411** [comment]
I mean it does not show any error in console.

**Comment by ian-r-rose** [comment]
What console are you using? I can see it using `bash`.

**Comment by ian-r-rose** [comment]
It does not seem to show up using PowerShell, however.

**Comment by vahedi25411** [comment]
Anaconda Prompt.

**Comment by ian-r-rose** [comment]
@vahedi25411 Can you check if #38 fixes the error output issue?

**Comment by vahedi25411** [comment]
Right now it shows error for me. But the error is different here :

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\Scripts\automated-walk-bike-counter-script.py", line 11, in <module>
    load_entry_point('automated-walk-bike-counter', 'console_scripts', 'automated-walk-bike-counter')()
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\app.py", line 34, in main
    app = Application()
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\app.py", line 26, in __init__
    self.view = MainView(root, self.controller)
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\view\main.py", line 32, in __init__
    self.view_initializer()
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\view\main.py", line 40, in view_initializer
    self.initialize_menu()
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\view\main.py", line 66, in initialize_menu
    App_Menu(self.parent, self.controller)
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\widgets\menu.py", line 37, in __init__
    menu_source.add_checkbutton(label='Built-in Webcam', command=self.built_in_webcam_selected, onvalue=1, offvalue=0, variable=self.controller.internal_webcam)
AttributeError: 'App_Menu' object has no attribute 'controller'

**Comment by ian-r-rose** [comment]
Okay, but with that you can see the errors and move forwards with the branch, right?

**Comment by vahedi25411** [comment]
Yes, Thanks

**Comment by vahedi25411** [comment]
How should I set the location of weights? You didn't mention anything about it in your help.

When I run the app I get this error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\gui\controller\main_controller.py", line 72, in update_video_canvas
    tracker.trackObjects(config)
  File "c:\users\mvahedi.et-eta408-lm1\documents\object_detection_project\github_final_ver_match_new\automated-walk-bike-counter\automated_walk_bike_counter\core\tracking\object_tracker.py", line 427, in trackObjects
    saver.restore(sess, args.restore_path)
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\site-packages\tensorflow\python\training\saver.py", line 1266, in restore
    if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\site-packages\tensorflow\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 372, in checkpoint_exists
    if file_io.get_matching_files(pathname):
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 361, in get_matching_files
    return get_matching_files_v2(filename)
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 389, in get_matching_files_v2
    for single_filename in pattern
  File "C:\ProgramData\Anaconda3\envs\automated-walk-bike-counter\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 's3' not implemented (file: 's3://automated-walk-bike-counter/yolo/yolov3.ckpt.index')

**Comment by ian-r-rose** [comment]
You can customize it with a `config.ini` or with a command line argument. For the former, make the following config and enter
```ini
[STORAGE_SETTINGS]
restore_path = /path/to/your/checkpoint
```
and start the app with `automated-walk-bike-counter --config=config.ini`.

For the latter, start  the app with `automated-walk-bike-counter --restore_path=/path/to/your/checkpoint`.

What version of tensorflow do you have installed? I'm using `1.13.1`, and reading from s3 seems to work okay.

**Comment by vahedi25411** [comment]
In the environment that I have created for the app according to your readme file, the TensorFlow version is `1.13.1`.

**Comment by vahedi25411** [comment]
Should the restore_path be relative to the location of the installation?

**Comment by ian-r-rose** [comment]
It can either be absolute, or relative to the directory in which you invoke the application.

**Comment by vahedi25411** [comment]
DataLossError (see above for traceback): Unable to open table file C:\Users\mvahedi.ET-ETA408-LM1\Documents\Object_Detection_Project\YOLOv3_TensorFlow\data\yolo_weights: Unknown: NewRandomAccessFile failed to Create/Open: C:\Users\mvahedi.ET-ETA408-LM1\Documents\Object_Detection_Project\YOLOv3_TensorFlow\data\yolo_weights : Access is denied.

**Comment by vahedi25411** [comment]
I run the app as an administrator using conda prompt and I get the above error.

**Comment by ian-r-rose** [comment]
Why are you running as administrator? That is usually a way to get permissions errors.

**Comment by vahedi25411** [comment]
In order to have permission to access the weight files.

**Comment by ian-r-rose** [comment]
Why do the weight files require administrator priveleges? Don't you own them?

**Comment by vahedi25411** [comment]
If the app can easily access any location inside the computer, then the computer would be vulnerable.

**Comment by ian-r-rose** [comment]
Sure, but can't you set the permissions on the weight files so that you own them?

**Comment by ian-r-rose** [comment]
This shouldn't really be different from what it was before: the app has always needed permissions to access the weights file

**Comment by vahedi25411** [comment]
Yes, but right now I want to make sure that the problem is related to permission. When I run it as administrator, it means that it will have the appropriate permission to access the weight file but still, I get the access denied error.

**Comment by ian-r-rose** [comment]
I think the problem may have something to do with configuring tensorflow on Windows. I see the s3 issue with Anaconda Prompt, but it works fine with WSL bash.

**Comment by ian-r-rose** [comment]
Possibly a relevant issue: https://github.com/tensorflow/tensorflow/issues/19297

We may want to download and cache the weights ourselves, if tf won't do it on Windows.
Does it work for you if you use WSL?

**Comment by vahedi25411** [comment]
Not yet, I was trying to fix the error and run it on Anaconda.

**Comment by ian-r-rose** [comment]
Closing as resolved. There is more work to do on real-time video (cf #88), but we can create new issues for those.
