### ISSUE TITLE
Create CSV output for remainder of time

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#58]
If the video has a length that doesn't divide evenly into the interval, we should still output results for the last bin of time. This is especially relevant for shorter videos, since it is the difference between some output and no output.

**Comment by ian-r-rose** [comment]
Any updates here @vahedi25411?

**Comment by vahedi25411** [comment]
Sorry, I forgot to push.

**Comment by ian-r-rose** [comment]
Fixed by #59
