### ISSUE TITLE
Area of non-interest / line of interest

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/automated-walk-bike-counter#78]
Does this code exist anywhere? I'd still like to see work-in-progress and test code that falls within the scope of the project pushed to this repository, otherwise I have no idea what the CSULA team is working on.

**Comment by vahedi25411** [comment]
@ian-r-rose I pushed the area of non-interest. I am still working on line of interest and I will push the changes shortly as well.

**Comment by ian-r-rose** [comment]
Partially fixed in #83. For a follow-up:

* In the AONI dialog it is still called "Area of Interest"
* There are some AOI related options in the left pane (opacity, etc). Should we add corresponding options for AONI?
* Add to CLI

**Comment by vahedi25411** [comment]
The first issue addressed in #89 
The answer to the second issue is No because we don't want to see anything about the AONI, we just don't want to see anything in that area, so we don't need to have an option for it.
