### ISSUE TITLE
README number renders weirdly. 

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/automated-walk-bike-counter#91]

**Comment by ian-r-rose** [comment]
Which number?

**Comment by hunterowens** [comment]
![image](https://user-images.githubusercontent.com/1735650/85324578-f48d4780-b47e-11ea-9d81-18ad7fc4155b.png)

**Comment by ian-r-rose** [comment]
Ah, got it, messed up the interaction with code fences and markdown numbering.
